In [1]:
import numpy as np

In [2]:
# Observations
P = np.array([[+2.00, +0.00, +1.00],
              [+1.08, +1.68, +2.38],
              [-0.83, +1.82, +2.49],
              [-1.97, +0.28, +2.15],
              [-1.31, -1.51, +2.59],
              [+0.57, -1.91, +4.32]], dtype=float)
print(P)

[[ 2.    0.    1.  ]
 [ 1.08  1.68  2.38]
 [-0.83  1.82  2.49]
 [-1.97  0.28  2.15]
 [-1.31 -1.51  2.59]
 [ 0.57 -1.91  4.32]]


In [4]:
# Time
T = np.array([[x ** n for n in range(3)] for x in [1, 2, 3, 4, 5, 6]]).reshape(len(P), -1)
# print(X)


# Model Weights
W = np.ones((3, 3))


# print(W)


# def linear_gradient(objective_arguments):
#     # This is the derivative of the objective function with respect to each weight.
#     return np.array([[12 * objective_arguments[0, 0] +  42 * objective_arguments[1, 0] +   23 / 25],
#                      [42 * objective_arguments[0, 0] + 182 * objective_arguments[1, 0] +  467 / 25],
#                      [12 * objective_arguments[0, 1] +  42 * objective_arguments[1, 1] -   18 / 25],
#                      [42 * objective_arguments[0, 1] + 182 * objective_arguments[1, 1] +  907 / 50],
#                      [12 * objective_arguments[0, 2] +  42 * objective_arguments[1, 2] - 1493 / 50],
#                      [42 * objective_arguments[0, 2] + 182 * objective_arguments[1, 2] -  607 /  5]], dtype=float).reshape((3, 2)).T


# def quadratic_gradient(objective_arguments):
#     # This is the derivative of the objective function with respect to each weight.
#     return np.array([[ 12 * objective_arguments[0, 0] +  42 * objective_arguments[1, 0] +  182 * objective_arguments[2, 0] +   23 / 25],
#                      [ 42 * objective_arguments[0, 0] + 182 * objective_arguments[1, 0] +  882 * objective_arguments[2, 0] +  467 / 25],
#                      [182 * objective_arguments[0, 0] + 882 * objective_arguments[1, 0] + 4550 * objective_arguments[2, 0] +  449 /  5],
#                      [ 12 * objective_arguments[0, 1] +  42 * objective_arguments[1, 1] +  182 * objective_arguments[2, 1] -   18 / 25],
#                      [ 42 * objective_arguments[0, 1] + 182 * objective_arguments[1, 1] +  882 * objective_arguments[2, 1] +  907 / 50],
#                      [182 * objective_arguments[0, 1] + 882 * objective_arguments[1, 1] + 4550 * objective_arguments[2, 1] + 7893 / 50],
#                      [ 12 * objective_arguments[0, 2] +  42 * objective_arguments[1, 2] +  182 * objective_arguments[2, 2] - 1493 / 50],
#                      [ 42 * objective_arguments[0, 2] + 182 * objective_arguments[1, 2] +  882 * objective_arguments[2, 2] -  607 /  5],
#                      [182 * objective_arguments[0, 2] + 882 * objective_arguments[1, 2] + 4550 * objective_arguments[2, 2] - 2876 /  5]], dtype=float).reshape((3, 3)).T


# print(quadratic_gradient(W))


def gradient(objective_arguments):
    # dE/dW = 2X(XW-T) using the chain rule, but the dimensions of X and (XW-T) are not compatible, so X is transposed.
    return 2 * T.T @ (T @ objective_arguments - P)


# Constant speed solution:
#      1.4693    2.1260    0.7993
#     -0.4417   -0.5903    0.4826
# Constant acceleration solution:
#       5.5160   -0.8940    1.3110
#      -3.4767    1.6747    0.0988
#       0.4336   -0.3236    0.0548
def gradient_descent(objective_arguments, objective_gradient, learning_rate=1e-5, max_num_iterations=1e+10,
                     step_eps=1e-15):
    for i in range(int(max_num_iterations)):
        step = learning_rate * objective_gradient(objective_arguments)
        if np.amax(np.abs(step)) < step_eps:
            break
        objective_arguments -= step
    return objective_arguments


print("Model Weights:\n", gradient_descent(W, gradient))
print("Actual Solution:\n", np.linalg.inv(T.T @ T) @ T.T @ P)
print("Residual Error:\n", np.sum((P - T @ W) ** 2))

Model Weights:
 [[ 5.516      -0.894       1.311     ]
 [-3.47671429  1.67471429  0.09882143]
 [ 0.43357143 -0.32357143  0.05482143]]
Actual Solution:
 [[ 5.516      -0.894       1.311     ]
 [-3.47671429  1.67471429  0.09882143]
 [ 0.43357143 -0.32357143  0.05482143]]
Residual Error:
 4.941977857142859
